name: VMSWEB
favicon: null
layout_spectrum: 0.24399
typography_spectrum: 0.44376
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#121011'
    - '#80aa49'
    - '#41433c'
    - '#6a795b'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
