name: VMSWEB
favicon: null
layout_spectrum: 0.25265
typography_spectrum: 0.3265959722921252
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#121011'
    - '#80aa49'
    - '#41433c'
    - '#6a795b'
  brandStrength: 0.5625
  lightness: 0.5245670930016786
  saturation: 0.615364741301164
  rhythmicContrast: 0.5545889416243881
purpose: []
